export const texts ={
  dashboard:{"pt-PT":"Painel","en-US":"Dashboard"},
  home:{"pt-PT":"Casa","en-US":"Home"},
  aboutUsTitle:{"pt-PT":"Sobre nós","en-US":"About-us"},
  termsOfConditionTitle:{"pt-PT":"Termos de condição","en-US":"Terms of condition"},
  privacyPolicyTitle:{"pt-PT":"Política de Privacidade","en-US":"Privacy policy"},
  contactUsTitle:{"pt-PT":"Contacte nos","en-US":"Contact us"},
  subscribeText:{"pt-PT":"Cadastre-se para receber novidades em primeira mão.","en-US":"Sign up to receive news first hand."},
  subscribe:{"pt-PT":"Inscrever-se","en-US":"Subscribe"},
  now:{"pt-PT":"agora","en-US":"now"},
  yesAndNot:{"pt-PT":["Sim","Não"],"en-US":["Yes","Not"]},
  active:{"pt-PT": "Ativo","en-US":"Active"},
  inactive:{"pt-PT": "Inativo","en-US":"Inactive"},
  findOutMore:{"pt-PT":"Descubra mais", "en-US":"Find out more"},
  and:{"pt-PT":"e","en-US":"and"},
  edit:{"pt-PT":"Editar","en-US":"Edit"},
  footerTitleC:{"pt-PT":"Contatos","en-US":"Contacts"},
  startNow:{"pt-PT": "Começar agora","en-US":"Start now"},
  max:{"pt-PT":"Máxima","en-US":"Maximum"},
  min:{"pt-PT":"Mínimo","en-US":"Minimum"},
  notFoundTitle:{"pt-PT":"Parece que você está perdido", "en-US":"Looks like you're lost"},
  notFoundtext:{"pt-PT": "A página que você está procurando não está disponível!", "en-US":"The page you are looking for is not available!"},
  goToBack:{"pt-PT":"Voltar para atrás", "en-US":"Go to back"},
  copyrigths:{"pt-PT":"Todos os direitos reservados","en-US":"All rights reserved."},
  makePublic:{"pt-PT":"Publicar","en-US":"Make public"},
  newReviewTitle:{"pt-PT":"Dê-nos a sua opinião","en-US":"Give us your opinion"},
  containHtml:{"pt-PT":"Caracteres especiais detectados, por favor revise este campo","en-US":"Special characters detected, please review this field"},
  seeMore:{"pt-PT":"Ver mais","en-US":"See more"},
  totalPages:{"pt-PT":"Total de páginas","en-US":"Total pages"},
  
  updateTitle:{"pt-PT":"Atualizar","en-US":"Update"},
  name:{"pt-PT":"Nome","en-US":"Name"},
  accountOwner:{"pt-PT":"Proprietário da conta", "en-US":"Account owner"},
  percentage:{"pt-PT":"Percentagem","en-US":"Percentage"},
  cannotBe0OrNull:{"pt-PT":"não pode ser 0 ou nulo","en-US":"cannot be 0 or null"},
  _delete:{"pt-PT":"Excluir","en-US":"Delete"},
  confirmLogOut:{"pt-PT":"Tens certeza que deseja sair?","en-US":"Are you sure you want to leave?"},
  doNotPublish:{"pt-PT":"Não publique","en-US":"Do not publish"},
  confirmsUser:{"pt-PT":["Tens certeza que deseja", "este usuário?"],"en-US":["Are you sure you want to","this user?"]},
  dangerBanUser:{"pt-PT":"Ao banir este usuário significa que ele ainda pode fazer login, mas não vai poder realizar certas operações.","en-US":"By banning this user it means that he can still log in, but will not be able to perform certain operations."},
  reactivate:{"pt-PT":"Reativar","en-US":"Reactivate"},
  userUpdatedSuccessfully:{"pt-PT":["Usuário","com sucesso."],"en-US":["User" ,"successfully."]},
  reactivated:{"pt-PT":"Reativado", "en-US":"Reactivated"},
  banned:{"pt-PT":"Banido", "en-US":"Banned"},
  
  amount:{"pt-PT":"Valor", "en-US":"Amount"},
  accountNumberTitle:{"pt-PT":"Número da conta","en-US":"Account number"},
  account:{"pt-PT":"Conta","en-US":"Account"},
  saveThisAccountTitle:{"pt-PT":"Guardar essa conta para utilizar nas próximas transações?","en-US":"Save this account to use in future transactions?"},
  invalid:{"pt-PT":"Inválido", "en-US":"Invalid"},
  accountAlreadyUsed:{"pt-PT":"Esta conta já está em uso por outro usuário.","en-US":"This account is already in use by another user."},
  thankYou:{"pt-PT":"Obrigado(a)","en-US":"Thank you"},
  orderWasPlaced:{"pt-PT":"O seu pedido foi realizado com sucesso","en-US":"Your order was placed successfully"},
  sorry:{"pt-PT":"Desculpa","en-US":"Sorry"},
  requestWasRejected:{"pt-PT":"O seu pedido foi rejeitado.", "en-US":"Your request was rejected"},
  unableToFulfill:{"pt-PT":"Infelizmente não conseguimos atender sua solicitação.","en-US":"Unfortunately we were unable to fulfill your request."},
  hasBeenBanned:{"pt-PT":"Sua conta foi banida nesta plataforma.","en-US":"Your account has been banned on this platform."},
  hasBeenReactivated:{"pt-PT":"Sua conta foi reativada, agora você pode realizar suas atividades na plataforma.", "en-US":"Your account has been reactivated, you can now carry out your activities on the platform."},
  _continue:{"pt-PT": "Continuar","en-US":"Continue"},
  fee:{"pt-PT":"Taxa", "en-US":"Fee"},
  important:{"pt-PT":"Importante","en-US":"Important"},
  
  
  timeUnits:{"pt-PT":["Agora","minuto","hora","dia","mês","ano"],"en-US": ["now","minute","hour","day","month","year"]},
  ago:{"pt-PT":"atrás","en-US":"ago"},
  gretings:{"pt-PT": "Olá!", "en-US":"Hello!"},
  loadingMsg:{"pt-PT":"Carregando...","en-US":"Loading..."},
  searchByUserId:{"pt-PT":"Pesquisar por ID de usuário","en-US":"Search by user id"},
  searchByDataId:{"pt-PT":"Pesquisar por ID","en-US":"Search by id"},
  search:{"pt-PT":"Pesquisar","en-US":"Search"},
  viewSource:{"pt-PT":"Ver a origem","en-US":"View source"},
  Pending:{"pt-PT":"Pendente","en-US":"Pending"},
  Rejected:{"pt-PT":"Rejeitado","en-US":"Rejected"},
  Voided:{"pt-PT":"Anulado", "en-US":"Voided"},
  Reject:{"pt-PT":"Rejeitar","en-US":"Reject"},
  Void:{"pt-PT":"Anular","en-US":"Void"},
  Inprogress:{"pt-PT":"Em andamento","en-US":"Inprogress"},
  Completed:{"pt-PT":"Concluído","en-US":"Completed"},
  cancel:{"pt-PT":"Cancelar","en-US":"Cancel"},
  Confirm:{"pt-PT":"Confirmar","en-US":"Confirm"},
  RejectParag:{"pt-PT":"Tens certeza que deseja rejeitar esse","en-US":"Are you sure you want to reject this"},
  tryAgain:{"pt-PT":"Tente novamente","en-US":"Try again "},
  contactSupport:{"pt-PT":"Contactar suporte", "en-US":"Contact support"},
  confirmedSuccessfully:{"pt-PT":"confirmado com sucesso.", "en-US":"successfully confirmed."},
  CompletedSuccessfully:{"pt-PT":"concluído com sucesso.", "en-US":"successfully completed."},
  VoidedSuccessfully:{"pt-PT":"revertido com sucesso.", "en-US":"successfully reversed."},
  RejectedSuccessfully:{"pt-PT":"rejeitado com sucesso.","en-US":"rejected successfully."},
  support:{"pt-PT":"Suporte", "en-US":"Support"},
  startAConversation:{"pt-PT":"Inicia uma conversar","en-US":"Start a conversation."},
  createdAt:{"pt-PT":"Criado em", "en-US":"Created at"},
  showToThePublic:{"pt-PT":"Mostrar para o público","en-US":"Show to the public"},
  nothingWasFound:{"pt-PT":"Nada foi encontrado!", "en-US":"Nothing was found!"},
  userInfos:{"pt-PT":"Informação de usuário","en-US":"User infos"},
  emailAddress:{"pt-PT":"Endereço de email","en-US":"Email address"},
  memberSince:{"pt-PT":"Membro desde","en-US":"Member since"},
  location:{"pt-PT":"Localização","en-US":"Location"},
  ProfileID:{"pt-PT":"ID do perfil","en-US":"Profile ID"},
  settings:{"pt-PT":"Configurações", "en-US": "Settings"},
  logout:{"pt-PT":"Sair","en-US":"Logout"},
  changePassword:{"pt-PT":"Trocar senha","en-US":"Change password"},
  balance:{"pt-PT":"Saldo","en-US":"Balance"},
  balanceAvailable:{"pt-PT":"Saldo disponível","en-US":"Balance available"},
  phoneNumber:{"pt-PT":"Número de Telefone","en-US":"Phone number"},
  notProvidedYet:{"pt-PT":"Ainda não fornecido","en-US":"Not provided yet"},
  imageNotsupported:{"pt-PT":"O arquivo selecionado não é suportada!","en-US":"The selected file is not supported!"},
  imageProfile:{"pt-PT":"Imagem de perfil","en-US":"Profile image"},
  image:{"pt-PT":"Imagem","en-US":"Image"},
  actionNotAllowed:{"pt-PT":"Ação não permitido.","en-US":"Action not allowed."},
  errorGettingCroppedImg:{"pt-PT":"Erro ao obter a imagem cortado.","en-US":"Error getting cropped image."},
  cropperIsNotResponding:{"pt-PT":"O cortador de imagens não está respondendo.","en-US":"Image cropper is not responding."},
  imagens:{"pt-PT":"Imagems","en-US":"Imagens"},
  editName:{"pt-PT":"Editar o nome","en-US":"Edit Name"},
  editPhoneNumber:{"pt-PT":"Editar número de telefone","en-US":"Edit phone number"},
  fullName:{"pt-PT":"Nome completo","en-US": "Full name"},
  invalidEmail:{"pt-PT":"Endereço de e-mail inválido!","en-US":"Invalid email!"},
  invalidFullName:{"pt-PT":"Nome completo inválido", "en-US":"Invalid full name"},
  invalidPhoneNumber:{"pt-PT":"Número de telefone inválido","en-US":"Invalid phone number"},
  deleteAccount:{"pt-PT":"Deletar esta conta","en-US": "Delete this account"},
  successfulDeletetAccount:{"pt-PT":"Conta deletado com sucesso.","en-US": "Account deleted successful."},
  successfulPasswordChenged:{"pt-PT":"Senha alterado com sucesso.","en-US":"Password changed successfully."},
  save:{"pt-PT":"Salvar","en-US": "Save"},
  resetPasswordTitle:{"pt-PT":"Redefinir senha","en-US":"Reset password"},
  welcomeBack:{"pt-PT":"Bem-vindo de volta!","en-US":"Welcome back!"},
  welcome:{"pt-PT":"Bem-vindo!","en-US":"Welcome!"},
  toBeLogging:{"pt-PT":"Ao fazer o login, você concorda com a nossa","en-US":"By logging in, you agree with our"},
  byRegistering:{"pt-PT":"Ao se cadastrar você concorda com os nossos","en-US":"By registering you agree to our"},
  byRequesting:{"pt-PT":"Ao solicitar uma redefinição de senha você concorda com nossos","en-US":"By requesting a password reset you agree to our"},
  byResetting:{"pt-PT":"Ao redefinir senha você concorda com nossos","en-US":"By resetting password you agree to our"},
  passwordLabel:{"pt-PT":"Senha", "en-US":"Password"},
  repeatPasswordLabel:{"pt-PT":"Repete a senha","en-US": "Repeat password"},
  invalidPassword:{"pt-PT":"Senha inválido","en-US":"Invalid password!"},
  passwordDontMatch:{"pt-PT":"As senhas não combinam!", "en-US":"Password don't match!"},
  emailAlreadyInUse:{"pt-PT":"O endereço de e-mail já está em uso por outra conta!" ,"en-US":"The email address is already in use by another account"},
  wrongPassword:{"pt-PT":"Senha incorreta","en-US":"Wrong password!"},
  tooManyRequests:{"pt-PT":"O acesso a esta conta foi temporariamente desabilitado devido a muitas tentativas de login malsucedidas. Você pode restaurá-lo imediatamente redefinindo sua senha ou pode tentar novamente mais tarde.","en-US":"Access to this account has been temporarily disabled due to many failed login attempts. You can immediately restore it by resetting your password or you can try again later."},
  requiresRecentLogin:{"pt-PT":"Esta operação é sensível e requer autenticação recente. Faça login novamente antes de tentar novamente esta solicitação.","en-US":"This operation is sensitive and requires recent authentication. Please log in again before retrying this request."},
  userNotFound:{"pt-PT":"Usuário não cadastrado!","en-US":"User not registered!"},
  weakPassword:{"pt-PT":"A senha deve ter pelo menos 6 caracteres", "en-US":"Password should be at least 6 characters!"},
  networkRequestFailed:{"pt-PT":"Falha na conexão a internet.","en-US":"Internet connection failure."},
  badNetwork:{"pt-PT":"Conexão muito lenta","en-US":"Connection very slowly"},
  dontHaveAccount:{"pt-PT":"Não tens uma conta?", "en-US":"Don't have account?"},
  resend:{"pt-PT":"Reenviar novamente","en-US":"Resend again"},
  sendConfirmationEmail:{"pt-PT":"Enviamos lhe um email de confirmação da conta, por favor verifique a sua caixa de emails.","en-US":"We have sent you an account confirmation email, please check your inbox."},
  verifyYourAccount:{ "pt-PT":"Verifique a sua conta", "en-US":"Verify your account"},
  iHaveAccount:{"pt-PT":"Já tem uma conta?", "en-US": "Already have an account?"},
  forgotPassword:{"pt-PT":"Esqueceu sua senha?", "en-US":"Forgot password?"},
  request:{"pt-PT":"Solicitar", "en-US":"Request"},
  requestSent:{"pt-PT":"Solicitação enviada, por favor verifique a sua caixa de emails", "en-US":"Request sent, please check your email inbox"},
  rememberPassword:{"pt-PT":"Lembra da sua senha?","en-US":"Do you remember your password?"},
  InvitesAfriend:{"pt-PT":"Convidar amigo","en-US":"Invite a friend"},
  me:{"pt-PT":"Eu","en-US":"My"},
  commissionAmount:{"pt-PT":"Comissão ganhada","en-US":"Earned commission"},
  invitedMembers:{"pt-PT":"Membros convidados","en-US":"Invited members"},
  activesMembers:{"pt-PT":"Membro Ativos","en-US":"Actives members"},
  thisMonth:{"pt-PT":"Este mês","en-US":"This month"},
  thisWeek:{"pt-PT":"Essa semana","en-US":"This week"},
  date:{"pt-PT":"Data","en-US":"Date"},
  users:{"pt-PT":"Usuários","en-US":"Users"},
  totalUsers:{"pt-PT":"Usuários totais","en-US":"Total users"},
  administrators:{"pt-PT":"Administradores","en-US":"Administrators"},
  bannedUsers:{"pt-PT":"Usuários banidos","en-US":"Banned users"},
  ban:{"pt-PT":"Banir","en-US":"Ban"},
  notifications:{"pt-PT":"Notificações","en-US":"Notifications"},
  unreadMessages:{"pt-PT":["Você tem","mensagens não lidas."] , "en-US":["You have","unread messages."]},
  lastSeen:{"pt-PT":"Visto há","en-US":"Seen"},
  typing:{"pt-PT":"digitando...","en-US":"typing..."},
  text:{"pt-PT":"Texto","en-US":"Text"},
  searchChat:{"pt-PT":"Procurar chat","en-US":"Search chat"},
  heSentYouAPhoto:{"pt-PT":"Mandou uma foto 📷","en-US":"He sent you a photo 📷"},
  YouSentAPhoto:{"pt-PT":"Enviaste uma foto 📷","en-US":"You sent a photo 📷"},
  sendMessage:{"pt-PT":"Enviar mensagem","en-US":"Send message"},
  clearThisConversation:{"pt-PT":"Limpar essa conversa","en-US":"Clear this conversation"},
  confirmClearConversation:{"pt-PT":"Tens certeza que deseja limpar esta conversa?","en-US":"Are you sure you want to clear this conversation?"},
  clearNow:{"pt-PT":"Limpar agora","en-US":"Clear now"},
  chatClearedCuccessfully:{"pt-PT":"Conversa limpado com sucesso.","en-US":"Conversation cleared successfully."},
  confirmRemoveMsg:{"pt-PT":"Pretende eliminar essa mensagem?","en-US":"Do you want to delete this message?"},
  cannotBeUndone:{"pt-PT":"Essa ação não pode ser anulada","en-US":"This action cannot be undone"},
  viewProfile:{"pt-PT":"Ver o perfil","en-US":"View profile"},
  selected:{"pt-PT":"selecionados","en-US":"selected"},
  occuredError:{"pt-PT":"Houve um erro!","en-US":"Occured error"},
  menuList: {
    languages: [
      { label:{"pt-PT":"Português","en-US":"Portuguese"}, value: "pt-PT" },
      { label:{"pt-PT":"Inglês","en-US":"English"}, value: "en-US" }
    ],
    themes: [
      { label:{"pt-PT":"Dia","en-US":"Day"}, value: "light" },
      { label:{"pt-PT":"Noite","en-US":"Night"}, value: "dark" }
    ],
    menu:[
      {label:{"pt-PT":"Mensagems","en-US":"Messages"}, link: "/admin/support"},
      {label:{"pt-PT":"Definicões","en-US":"Settings"}, link:"/admin/settings"}
    ]
  }
}